"""
Agent state definition for the LangGraph workflow.

The state is a TypedDict that flows through all nodes in the graph.
Each node reads from and writes to specific fields in the state.
"""

from __future__ import annotations

from typing import Annotated, Optional, TypedDict

from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """
    State that flows through the LangGraph portal context agent.

    Fields:
        documents: List of parsed document dicts (filename, content, file_type).
        user_inputs: Free-text inputs provided by the user.
        messages: Chat history (LangGraph managed, supports add_messages reducer).
        analysis: LLM's analysis of the uploaded documents.
        portal_context: Generated portal info dict (for _portal_info.json).
        workflows: List of generated workflow dicts.
        questions: Clarifying questions generated by the LLM.
        user_answers: User's answers to clarifying questions.
        feedback: User feedback on the generated JSON (for refinement).
        phase: Current agent phase — tracks progress in the UI.
        iteration: Number of refinement iterations completed.
        error: Error message if something went wrong.
    """
    documents: list[dict]
    user_inputs: list[str]
    messages: Annotated[list, add_messages]
    analysis: Optional[str]
    portal_context: Optional[dict]
    workflows: list[dict]
    questions: list[str]
    user_answers: list[str]
    feedback: Optional[str]
    phase: str
    iteration: int
    error: Optional[str]
